name: HuuHungSAMP
options:
  deploymentTarget:
    iOS: "14.0"
targets:
  HuuHungSAMP:
    type: application
    platform: iOS
    sources: [HuuHungSAMP]
    settings:
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_ALLOWED: NO
      CLANG_CXX_LANGUAGE_STANDARD: "c++17"
      CLANG_CXX_LIBRARY: "libc++"
      OTHER_CPLUSPLUSFLAGS: "$(inherited) -ObjC -Wno-trigraphs"
