import UIKit
final class HuuHungSAMPViewController:UIViewController{
 private let nick=UITextField(),host=UITextField(),port=UITextField(),status=UILabel(),logView=UITextView();private let client=HHSampClient()
 override func viewDidLoad(){super.viewDidLoad();view.backgroundColor=UIColor(white:0.035,alpha:1);build()}
 private func field(_ f:UITextField,_ p:String)->UITextField{f.placeholder=p;f.textColor=.white;f.tintColor=.white;f.backgroundColor=UIColor(white:0.12,alpha:1);f.layer.cornerRadius=10;f.heightAnchor.constraint(equalToConstant:48).isActive=true;f.leftView=UIView(frame:CGRect(x:0,y:0,width:12,height:1));f.leftViewMode=.always;return f}
 private func build(){let title=UILabel();title.text="HuuHungSAMP";title.textColor=.white;title.font=.systemFont(ofSize:34,weight:.heavy);let sub=UILabel();sub.text="SA-MP • GTA SA iOS 2.2.21";sub.textColor=.systemGray;let play=UIButton(type:.system);play.setTitle("PLAY ONLINE",for:.normal);play.titleLabel?.font=.boldSystemFont(ofSize:18);play.addTarget(self,action:#selector(playOnline),for:.touchUpInside);let off=UIButton(type:.system);off.setTitle("PLAY OFFLINE",for:.normal);off.addTarget(self,action:#selector(playOffline),for:.touchUpInside);status.text="Ready";status.textColor=.systemGray;logView.textColor=.lightGray;logView.backgroundColor=UIColor(white:0.08,alpha:1);logView.layer.cornerRadius=10;logView.heightAnchor.constraint(equalToConstant:110).isActive=true;let s=UIStackView(arrangedSubviews:[title,sub,field(nick,"Nickname"),field(host,"Server IP"),field(port,"Port (7777)"),play,off,status,logView]);s.axis=.vertical;s.spacing=10;s.translatesAutoresizingMaskIntoConstraints=false;view.addSubview(s);NSLayoutConstraint.activate([s.leadingAnchor.constraint(equalTo:view.safeAreaLayoutGuide.leadingAnchor,constant:24),s.trailingAnchor.constraint(equalTo:view.safeAreaLayoutGuide.trailingAnchor,constant:-24),s.centerYAnchor.constraint(equalTo:view.centerYAnchor)]);nick.text="HuuHung";host.text="127.0.0.1";port.text="7777"}
 @objc private func playOnline(){let p=UInt16(port.text ?? "7777") ?? 7777;client.net().setLog{[weak self]m in DispatchQueue.main.async{self?.status.text=m;self?.logView.text.append("\n"+m)}};status.text="Connecting…";_ = client.connect(host.text ?? "127.0.0.1",p,nick.text ?? "HuuHung");Timer.scheduledTimer(withTimeInterval:0.05,repeats:true){[weak self]t in guard let s=self else{t.invalidate();return};s.client.tick()}}
 @objc private func playOffline(){status.text="GTA SA offline mode"}
}
